### ISSUE TITLE
Drupal notice block.module

### ISSUE THREAD

**Issue by darkben** [heshanlk/OctopusVideo#1]
When the install is finished i have this error (repeated twice) on the homepage (and all others pages) :
Notice: Trying to get property of non-object in block_block_view() (line 245 of /var/www/monflux/modules/block/block.module).

Octopus version : 1.0-alpha3
PHP : PHP 5.3.2
Ubuntu : 10.04

**Comment by heshanlk** [comment]
Please update to the latest version of GitHub or make from the GitHub. This has been fixed.
