### ISSUE TITLE
Video.js module path is wrong

### ISSUE THREAD

**Issue by traubad** [heshanlk/OctopusVideo#13]
When you initially set up Octopus Video, it's looking for video.js in the wrong location.  The octopus vs octopus_video issue is still present.

**Comment by Bengt** [comment]
I can verify this. When running the recommended installation command

```
$ sudo drush make https://raw.github.com/heidisoft/Octopus/master/build-octopus-video.make octopus
```

the output contains this section

```
...
Unable to download video-js from                                     [error]
https://github.com/downloads/zencoder/video-js/video-js-3.2.0.zip.
...
```

The "video.js" repo has "moved permanently" from the organization "zencoder" to a organization "videojs" [github.com/videojs/video.js](https://github.com/videojs/video.js). Confer this:

```
$ LANG=en_US wget https://github.com/zencoder/video-js/
...
Connecting to github.com (github.com)|204.232.175.90|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/videojs/video.js/ [following]
...
```
