### ISSUE TITLE
Errors dowloading a few objects

### ISSUE THREAD

**Issue by osdal** [heshanlk/OctopusVideo#19]
Hello!
When I tried to install using command
$ drush make build-octopus-video.make
I've got a few errors unable to download:
1. jquery.cycle.all.js
2. jwplayer_skin_modieus
3. jwplayer_skin_snel
In result aborting install.
Help me please.

**Comment by Axl75mx** [comment]
Hello
I saw the same error when I tried to install the Octopus Distribution from the build-octopus-video.make script.

Unable to unzip /tmp/make_tmp_1435964269_5597136d0a85e/3.2.0.zip.                                                       [error]
ckeditor downloaded from http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.2/ckeditor_3.6.2.tar.gz.         [ok]
jquery.cycle downloaded from https://raw.github.com/malsup/cycle/master/jquery.cycle.all.js.                            [ok]
zencoder cloned from https://github.com/zencoder/zencoder-php.git.                                                      [ok]
Checked out tag v2.0.2.                                                                                                 [ok]
jwplayer downloaded from https://account.jwplayer.com/static/download/jwplayer-6.12.zip.                                [ok]
Unable to unzip /tmp/make_tmp_1435964269_5597136d0a85e/jwplayer-6.12.zip.                                               [error]
jwplayer_skin_snel downloaded from https://account.jwplayer.com/static/download/jwplayer-skins-free.zip.                [ok]
Unable to unzip /tmp/make_tmp_1435964269_5597136d0a85e/jwplayer-skins-free.zip.                                         [error]

I hope that you have enough time to fix it. Thank you.

**Comment by heshanlk** [comment]
Thanks. I’ll fix it.

**Comment by Axl75mx** [comment]
Great thanks. In the meantime and for testing purpose only I did comment those lines in installation. Regards.
