### ISSUE TITLE
can't play video after encoding process

### ISSUE THREAD

**Issue by darkben** [heshanlk/OctopusVideo#2]
I have installed Octopus from GIT and all seems to be ok : Amazon S3 and Zencoder are well configured : my video test is well uploaded on zencoder and amazon s3, the notification is ok but my video is not available on the homepage : when i click on the thumbnail i have the message : "This video is currently being processed. Please wait."
When i look at zencoder i can play my video from amazon s3. 
Status received in /postback/jobs HTTP/1.1 200 OK

**Comment by heshanlk** [comment]
Please check for Drupal logs. You should have a public hosting to receive postback request from Zencoder.

**Comment by darkben** [comment]
i have http://beta2.monflux.org/postback/jobs in "Postback URL for Zencoder" setting. I have created the folders and an html index.htm in jobs directory... http://beta2.monflux.org/postback/jobs is in public access but video is not available...

**Comment by heshanlk** [comment]
The what you have done is wrong. Do not create new files or folder in the path of /postback/jobs. Please remove all folders/files you have created. Drupal should be able to access that path. Please see your permissions to access the path in user permissions.
Please see Drupal logs for further debug.

**Comment by darkben** [comment]
Ok, i removed created folders /postback/jobs. Now i have another error when i upload a file : 
Notice : Trying to get property of non-object dans TranscoderAbstractionFactoryZencoder->processPostback() (ligne 360 dans /var/www/monflux/profiles/octopus/modules/contrib/video/transcoders/TranscoderAbstractionFactoryZencoder.inc).

I have this error in my apache2 error logs i have this :
[Wed Nov 23 10:28:53 2011] [error] [client 50.56.3.247] File does not exist: /var/www/monflux/postback

In permissions i have "Transcoder postback path access " checked for all users (anonymous too).

I have a notice error on zencoder :
Notification sent :
{"output":{"label":"video-20","url":"http://beta2.monflux.org.s3.amazonaws.com/videos/converted/20/webjalles_pieces_jointes_mp4_1322040074.mp4","id":10768429,"state":"finished"},"job":{"test":true,"id":8742546,"state":"finished"}}

Response Received
HTTP/1.1 404 Not Found
... 

My root folder (/var/www/monflux) is owned by www-data:www-data and is 777

**Comment by heshanlk** [comment]
Just try to direct access your postback url in browser and see what is the issue, Seems the post back url is not working. Please check the Trasncoder settings and postback path.

**Comment by darkben** [comment]
when i try to access my postback url I have a blank page. If i rename my .htaccess in htacess_off i have a 404 error. Transcoder settings are ok and postback path is http://beta2.monflux.org/postback/jobs
I don't understand... I will tried to reinstall...

**Comment by heshanlk** [comment]
Can you see any error on logs when you access postback path?. It seems something is wrong with your installation somehow Zencoder cannot postback your data so your videos will not update.

**Comment by darkben** [comment]
I have this error in drupal logs : Notice : Trying to get property of non-object dans TranscoderAbstractionFactoryZencoder->processPostback() (ligne 360 dans /var/www/monflux/profiles/octopus/modules/contrib/video/transcoders/TranscoderAbstractionFactoryZencoder.inc).

I have this error in apache log : [Wed Nov 23 13:20:08 2011] [error] [client 50.56.3.246] File does not exist: /var/www/monflux/postback

I have chmod 777 recursively my root site directory to test if that change anything and it is not ok... I'll tried another install

**Comment by heshanlk** [comment]
hmm. No idea. If you can contact me I can help you.

**Comment by darkben** [comment]
No idea too... I have tried to reinstall and i have same problem with Zencoder notifications : they can't access to postback/jobs... i can give you an admin access on my Drupal octopus install... But i think this is a server problem... I put a phpinfo file here http://beta2.monflux.org/phpinfo.php
thanks for your help

**Comment by darkben** [comment]
It's ok now ! mod_rewrite wasn't activated on my server :(
with 
a2enmod rewrite
and
/etc/init.d apache2 restart
notifications are sent by zencoder !
