### ISSUE TITLE
Install without zencoder

### ISSUE THREAD

**Issue by maldo81** [heshanlk/OctopusVideo#3]
I have ffmpeg installed and don't need zencoder and its kind of a hastle each time durring installation (call it retardation).  I am running out of emails to make zencoder accounts for clean installs I mean I guess I can make more on my hosting account.  Is there a way to bypass this part of the installation so that I don't have to do that?

**Comment by heshanlk** [comment]
There is no way to bypass, but I hope to remove that part and make it optional, so people can use FFmpeg. Once you install Octopus then you can switch to FFmpeg.
