### ISSUE TITLE
Register and Login links

### ISSUE THREAD

**Issue by darkben** [heshanlk/OctopusVideo#5]
when i'm not connected on Octopus i have no "register" and "login" links in user menu like on the demo.octopusvideo.org site. I have created another menu to have the two links because i can't add this on the user menu. How can i add these two links ?

**Comment by heshanlk** [comment]
You can add them to the 'user menu'

**Comment by darkben** [comment]
Ok, i tried again and i have my "Login " link... I have changed the weight and it's ok now... Thanks
