### ISSUE TITLE
ffmpeg issues only works once

### ISSUE THREAD

**Issue by maldo81** [heshanlk/OctopusVideo#6]
It works great, once.  Then it doesn't work, it still uploads the thumbnails to my folder, the original and converted video files but I get this message and then it wont save it.  Here is the error:   

An AJAX HTTP request terminated abnormally.
Debugging Information follows.
Path:
/file/ajax/field_video/und/0/form-eUOjss_Dv97qh7AACjkQa_ijUZHSW21m78WBpOouI8Y
StatusText: n/a
ResponseText: 
Fatal error: Call to a member function toGDImage() on a non-object in home/wavbange/public_html/profiles/octopus/modules/contrib/video/transcoders/TranscodersAbstractionFactoryFfmpeg.inc on line 145
ReadyState: Undefined.

I am not sure if this is an issue with my ffmpeg install or with something else, but if it was the install it wouldn't work once.  I am honestly stumped on this, any help would be great.

**Comment by yuseferi** [comment]
I have the sampe problem

**Comment by heshanlk** [comment]
This is appeared to be Ffmpeg issue. Closing.
